// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2hdMzJmbTQu4wD3nGDuRrywQ5qpPAgoA',
    appId: '1:877960725179:web:9d3d8e96a3add2d0201f9e',
    messagingSenderId: '877960725179',
    projectId: 'homewidget-3f161',
    authDomain: 'homewidget-3f161.firebaseapp.com',
    storageBucket: 'homewidget-3f161.firebasestorage.app',
    measurementId: 'G-4RLQC9B6GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqGKX0ycMJeXWbSLmaowDHEYTWoUWB0As',
    appId: '1:877960725179:android:547b01811e0ec919201f9e',
    messagingSenderId: '877960725179',
    projectId: 'homewidget-3f161',
    storageBucket: 'homewidget-3f161.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCvUqWuYlbLekVEQrrQK9NmSnsn22tfrw',
    appId: '1:877960725179:ios:4103c24f90da56b2201f9e',
    messagingSenderId: '877960725179',
    projectId: 'homewidget-3f161',
    storageBucket: 'homewidget-3f161.firebasestorage.app',
    iosBundleId: 'com.example.home',
  );
}
